#! /bin/sh
# /etc/init.d/infoscreen

### BEGIN INIT INFO
# Provides:          infoscreen
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Infoscreen Flask-Server
# Description:       This script starts/stops the Infoscreen Flask-Server
### END INIT INFO

# Author: Felix Doering <felix@ifsr.de>
#
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DIR=/home/pi/infoscreen/middleware
DESC="Infoscreen Flask-Server"
NAME=infoscreen
DAEMON=$DIR/$NAME.py
DAEMON_OPTS="production"
DAEMON_USER="pi"
LOGFILE=/home/pi/infoscreen.log
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

do_start()
{
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec $DAEMON $DAEMON_OPTS > $LOGFILE 2>&1"
    sleep 10
    export DISPLAY=:0
    xdotool key F5
}

#
# Function that stops the daemon/service
#
do_stop()
{
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm -f $PIDFILE
}

case "$1" in
  start)
    do_start
    sleep 35
    export DISPLAY=:0
    xdotool key F5
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  status)
    status_of_proc -p $PIDFILE "$NAME" && exit 0 || exit $?    ;;
  *)
    echo "$NAME\n$DESC\n\nUsage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0
